[tox]
requires =
    tox>=4
env_list =
    py{312,314}
    coverage
skip_missing_interpreters = true
no_package = true

[testenv]
description = run the tests with pytest
skip_install = true
setenv =
    PYTHONPATH = {toxinidir}/src/python
allowlist_externals = poetry
commands_pre =
    poetry install --no-root
commands =
    poetry run pytest {posargs:tests}

[testenv:coverage]
description = run coverage report
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install --no-root
commands = 
    poetry run pytest --cov=src/python --cov-report=term-missing --cov-report=html {posargs:tests}